repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-json
            exclude: ^tsconfig\.json
          - id: check-yaml
    - repo: https://github.com/prettier/prettier
      rev: 1.19.1
      hooks:
          - id: prettier
            name: prettier
            exclude: ^package\.json
    - repo: https://github.com/Yelp/detect-secrets
      rev: v0.13.0
      hooks:
          - id: detect-secrets
            args: ['--baseline', '.secrets.baseline']
            exclude: tests/.*
