language: node_js

dist: bionic

node_js:
    - '12'

before_install:
    # https://classic.yarnpkg.com/en/docs/install#alternatives-stable
    - curl -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.0
    - export PATH="$HOME/.yarn/bin:$PATH"
    - pyenv global 3.8

cache:
    yarn: true

install:
    - yarn

script:
    - make test
