typings:
    language: typescript
    embedResourcesType:
        imports: |
            import type { SWAPIClientlibTypes } from './swapi';
        ResourcesType: |
            type ResourcesType = SWAPIClientlibTypes;

resources:
    getPlanets:
        docsLink: https://swapi.info/documentation#planets
        isBatchResource: true
        batchKey: planet_ids
        newKey: planet_id
    getPeople:
        docsLink: https://swapi.info/documentation#people
        isBatchResource: true
        batchKey: people_ids
        newKey: person_id
    getVehicles:
        docsLink: https://swapi.info/documentation#vehicles
        isBatchResource: true
        batchKey: vehicle_ids
        newKey: vehicle_id
    getFilms:
        docsLink: https://swapi.info/documentation#films
        isBatchResource: true
        batchKey: film_ids
        newKey: film_id
        isBatchKeyASet: true
    getFilmsV2:
        docsLink: https://swapi.info/documentation#films
        isBatchResource: true
        batchKey: film_ids
        newKey: film_id
        nestedPath: properties
        propertyBatchKey: properties
        responseKey: id
    getRoot:
        docsLink: https://swapi.info/documentation#root
        isBatchResource: false
