typings:
    language: flow
    embedResourcesType:
        imports: |
            import type { SWAPIClientlibTypes } from './swapi';
        ResourcesType: |
            type ResourcesType = SWAPIClientlibTypes;

resources:
    getPlanets:
        docsLink: https://swapi.co/documentation#planets
        isBatchResource: true
        batchKey: planet_ids
        newKey: planet_id
    getPeople:
        docsLink: https://swapi.co/documentation#people
        isBatchResource: true
        batchKey: people_ids
        newKey: person_id
    getVehicles:
        docsLink: https://swapi.co/documentation#vehicles
        isBatchResource: true
        batchKey: vehicle_ids
        newKey: vehicle_id
    getRoot:
        docsLink: https://swapi.co/documentation#root
        isBatchResource: false
